### ISSUE TITLE
[feature] 디테일 가게정보_섹션 컴포넌트 UI

### ISSUE THREAD

**Issue by leeboa2005** [B05-group-plus-project/seongsimdangsajo#11]
## Description
디테일 가게정보_섹션 컴포넌트 UI
## To-Do

-   [x]  가게정보_섹션 컴포넌트 생성 
-   [x] 가게정보_섹션 이미지영역 UI 
-   [x] 가게정보_섹션 텍스트영역 UI 
-   [x] 가게정보_섹션 반응형 작업

### 작업이 완료 예정인 시점을 적어주세요
2024.07.09
