### ISSUE TITLE
[feature] like 테이블 연동

### ISSUE THREAD

**Issue by Dayeon-Cheon** [B05-group-plus-project/seongsimdangsajo#12]
## Description

like 테이블 연동

## To-Do

-   [x] like 테이블에 데이터 삽입
-   [x] like 테이블로부터 데이터 삭제
-   [x] 랜더링 시 좋아요 상태 체크 후 상태 변경
