### ISSUE TITLE
[STYLE] 전체 CSS 리팩토링 

### ISSUE THREAD

**Issue by leeboa2005** [B05-group-plus-project/seongsimdangsajo#120]
## Description
전반적인 CSS 수정 및 반응형 리팩토링

## To-Do
-   [x] 메인, 헤더, 마이페이지, 로그인, 회원가입 페이지 CSS 리팩토링 완료 (07.13)
-   [x] 디테일 페이지 미완료 
-   [x] 전체 CSS 리펙토링
-   [x] 반응형 CSS  리펙토링
