### ISSUE TITLE
[feature] 카드 리스트 로직 구현

### ISSUE THREAD

**Issue by heesu21** [B05-group-plus-project/seongsimdangsajo#33]
## To-Do

-   [ ] 베이커리 정보를 수파베이스에서 받아오는 로직구현
-   [ ] 받아온 정보 카드에 넣는 로직 구현
-   [ ]카드에 넣은 정보 메인에 뿌려주는 로직 구현
