### ISSUE TITLE
[FEATURE] 디테일 페이지 지도 영역 컴포넌트 작업

### ISSUE THREAD

**Issue by leeboa2005** [B05-group-plus-project/seongsimdangsajo#36]
## Description
디테일 페이지 지도 영역 컴포넌트 작업

## To-Do

-   [x] 지도 영역 컴포넌트 생성
-   [x] 카카오 API 연동
-   [x] 지도 영역 UI 완성하기 

### 작업이 완료 예정인 시점을 적어주세요
2024.07.10

**Comment by leeboa2005** [comment]
지도 기능 구현 완료
