### ISSUE TITLE
[feature] 댓글 컴포넌트 UI

### ISSUE THREAD

**Issue by MinKonKim** [B05-group-plus-project/seongsimdangsajo#4]
## Description
댓글 컴포넌트  UI

## To-Do
-   [x] 댓글 컴포넌트 생성
-   [x] 입력창 ui 제작
-   [x] 댓글 리스트 ui 제작
