### ISSUE TITLE
[UPDATE] 디테일 가게 정보 영역 데이터 받아오기 

### ISSUE THREAD

**Issue by leeboa2005** [B05-group-plus-project/seongsimdangsajo#53]
## Description
디테일 가게 정보 영역 데어터 받아오기 

## To-Do

-   [x] 디테일 가게 데이터 받아오기 
-   [x] 화면에 이상 없이 보이게 하기 
-   [x] 디테일 페이지 중복된 코드 제거, 디렉토리 구조 변경 

### 작업이 완료 예정인 시점을 적어주세요
2024.07.12

**Comment by leeboa2005** [comment]
디테일 페이지 가게정보 불러오기 및 리팩토링 완료
