### ISSUE TITLE
[FEATURE] 검색 기능

### ISSUE THREAD

**Issue by Dayeon-Cheon** [B05-group-plus-project/seongsimdangsajo#60]
## Description

검색 기능 구현

## To-Do

-   [x] 빵집 이름으로 검색
-   [x] 유효성 검사 (빈칸 허용하지 않음, 검색어 2자 이상)
-   [x] 엔터 누를 시 검색되도록 처리
-   [x] 검색 결과 페이지의 검색창에 검색 키워드 넣기
-   [x] 검색 결과 없을 경우 처리
-   [x] 검색 결과 건수 표시
