### ISSUE TITLE
[FEATURE] 유저정보 불러오기, 모달창에서 유저정보 수정

### ISSUE THREAD

**Issue by Elephant24456** [B05-group-plus-project/seongsimdangsajo#65]
## To-Do

-   [ ] 로그인한 유저의 정보 불러오기
-   [ ] 불러온 유저정보(프로필사진, 닉네임, 이메일) 모달창에서 수정기능 추가하기
-   [ ] 수정완료시 모달창을 닫고 마이페이지로 돌아가기
