### ISSUE TITLE
[FEATURE] 좋아요 리스트 표시하기

### ISSUE THREAD

**Issue by tpring** [B05-group-plus-project/seongsimdangsajo#76]
## To-Do

-   [x] `like` 테이블에서 `user_id`에 해당하는 `bakery_id` 가져오기
-   [x] `bakery` 테이블에서 `bakery_id`에 해당하는 정보를 가져오기
-   [x]  디테일 페이지 연동
