### ISSUE TITLE
[style] 메인 헤더 css

### ISSUE THREAD

**Issue by heesu21** [B05-group-plus-project/seongsimdangsajo#78]
## To-Do

-   [ ]카드이미지 크기고정
-   [ ]헤더 높이 조정
-   [ ]로고 클릭시 홈으로 이동
-   [ ]가로 스크롤 없애기
