### ISSUE TITLE
[UPDATE] 디테일 페이지 파라미터 부분 수정 및 404 처리 

### ISSUE THREAD

**Issue by leeboa2005** [B05-group-plus-project/seongsimdangsajo#86]
## Description
디테일 페이지 파라미터 부분 수정 및 404 처리 

## To-Do
-   [x] 디테일 페이지 파라미터로 데이터 받아오는 부분 수정 
-   [x] 404 페이지 처리 
-   [x] 404 동적 메타데이터 처리
-   [x] 지도 마커에 링크 추가

## up-to-date
2024.07.12
